webtalk_init -webtalk_dir C:/Users/Student/Downloads/project_Li/GROUP-8-FINAL/GROUP-8-FINAL.sim/sim_1/behav/xsim/xsim.dir/last_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Apr 30 22:43:28 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211204098_1777519307_210638372_969" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "952af41b-f089-420a-b0ff-d64e70568ab7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ffd5748e551444249e4d1df978f54489" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8500T CPU @ 2.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6748_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4247864221 -regid "211204098_1777519307_210638372_969" -xml C:/Users/Student/Downloads/project_Li/GROUP-8-FINAL/GROUP-8-FINAL.sim/sim_1/behav/xsim/xsim.dir/last_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Student/Downloads/project_Li/GROUP-8-FINAL/GROUP-8-FINAL.sim/sim_1/behav/xsim/xsim.dir/last_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Student/Downloads/project_Li/GROUP-8-FINAL/GROUP-8-FINAL.sim/sim_1/behav/xsim/xsim.dir/last_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
